import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './test-server.mjs';
import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';

test('账号全链路：审批、权限、房间归属、持久化、密码、封禁、审计和限流',async t=>{
 const f=await fixture();t.after(()=>f.close());
 const call=f.request;
 assert.equal((await call('/api',{op:'create'})).status,401);
 assert.equal((await call('/admin-api',{op:'status'})).status,401);
 assert.equal((await call('/auth',{op:'login',username:'test_admin',password:f.secret},'',{Origin:'https://evil.example'})).status,403);
 assert.equal((await call('/auth',{op:'login'},'',{'Content-Type':'text/plain'})).status,415);
 let login=await call('/auth',{op:'login',username:'test_admin',password:f.secret});
 assert.equal(login.data.user.xp,0);
 assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);let admin=login.cookie;
 const activityDb=new DatabaseSync(join(f.directory,'accounts.sqlite'));activityDb.prepare("UPDATE users SET last_active_at=1 WHERE username='test_admin'").run();activityDb.close();await call('/auth',{op:'me'},admin);const activityRead=new DatabaseSync(join(f.directory,'accounts.sqlite'),{readOnly:true}),firstActive=activityRead.prepare("SELECT last_active_at FROM users WHERE username='test_admin'").get().last_active_at;for(let i=0;i<8;i++)await call('/auth',{op:'me'},admin);const secondActive=activityRead.prepare("SELECT last_active_at FROM users WHERE username='test_admin'").get().last_active_at;activityRead.close();assert.equal(secondActive,firstActive,'高频请求不应反复写在线时间');
 assert.equal((await call('/auth',{op:'register',username:'alice',password:f.secret,nickname:'朋友甲',role:'admin',status:'active'})).status,200);
 assert.equal((await call('/auth',{op:'register',username:'ALICE',password:f.secret,nickname:'朋友甲'})).status,400);
 login=await call('/auth',{op:'login',username:'alice',password:f.secret});let alice=login.cookie;
 assert.equal((await call('/auth',{op:'profile',nickname:'改名朋友',userId:'other'},alice)).data.user.nickname,'改名朋友');
 assert.equal((await call('/auth',{op:'profile',nickname:'   '},alice)).status,400);
 assert.equal((await call('/auth',{op:'profile',nickname:'朋友甲'},alice)).status,200);
 assert.equal((await call('/auth',{op:'skin',cardBack:'ink'},alice)).data.user.card_back,'ink');
 assert.equal((await call('/auth',{op:'skin',cardBack:'invalid'},alice)).status,400);
 assert.equal(login.data.user.status,'pending');assert.equal(login.data.user.role,'user');
 assert.equal((await call('/api',{op:'create'},alice)).status,403);
 assert.equal((await call('/admin-api',{op:'status'},alice)).status,403);
 let status=(await call('/admin-api',{op:'status'},admin)).data;
 const id=status.users.find(u=>u.username==='alice').id;
 assert.equal((await call('/admin-api',{op:'statusChange',userId:id,status:'active'},admin)).status,200);
 assert.equal((await call('/admin-api',{op:'status'},alice)).status,403);
 const host=(await call('/api',{op:'create',name:'伪造昵称'},admin)).data;
 const member=(await call('/api',{op:'join',code:host.code,name:'伪造昵称'},alice)).data;
 const state=(await call('/api',{op:'state',...host},admin)).data;
 assert.equal(state.players[1].name,'朋友甲');assert(!JSON.stringify(state).includes(member.token));
 assert.equal((await call('/api',{op:'state',...member},admin)).status,400);
 assert.equal((await call('/api',{op:'close',...host},alice)).status,400);
 const again=(await call('/api',{op:'join',code:host.code},alice)).data;assert.equal(again.token,member.token);
 assert.equal((await call('/api',{op:'create'},alice)).status,400);
 assert.equal((await call('/auth',{op:'profile',nickname:'新昵称'},alice)).status,200);
 assert.equal((await call('/api',{op:'state',...host},admin)).data.players[1].name,'新昵称');
 await call('/api',{op:'start',...host},admin);
 status=(await call('/admin-api',{op:'status'},admin)).data;
 assert.equal(status.rooms.length,1);assert.equal(status.rooms[0].players[1].id,id);
 assert(!JSON.stringify(status).includes('cards'));assert(!JSON.stringify(status).includes('password_hash'));assert(!JSON.stringify(status).includes(host.token));
 assert.equal((await call('/admin-api',{op:'limit',limit:2},admin)).status,200);
 assert.equal((await call('/auth',{op:'register',username:'bob',password:f.secret,nickname:'朋友乙'})).status,400);
 const db=new DatabaseSync(join(f.directory,'accounts.sqlite'),{readOnly:true});
 const stored=db.prepare('SELECT password_hash FROM users WHERE id=?').get(id).password_hash;
 assert(stored.startsWith('scrypt:'));assert(!stored.includes(f.secret));db.close();
 await f.restart();
 assert.equal((await call('/auth',{op:'me'},alice)).data.user.status,'active');assert.equal((await call('/auth',{op:'me'},alice)).data.user.nickname,'新昵称');assert.equal((await call('/auth',{op:'me'},alice)).data.user.card_back,'ink');assert.equal((await call('/auth',{op:'me'},alice)).data.user.xp,0);
 status=(await call('/admin-api',{op:'status'},admin)).data;assert.equal(status.limit,2);assert(status.audit.some(x=>x.action==='active'));assert.equal(status.rooms.length,0);
 const oldCookie=alice;login=await call('/auth',{op:'login',username:'alice',password:f.secret});alice=login.cookie;
 assert.equal((await call('/auth',{op:'me'},oldCookie)).status,401);
 assert.equal((await call('/auth',{op:'password',oldPassword:f.secret,password:'012345'},alice)).status,200);
 assert.equal((await call('/auth',{op:'me'},alice)).status,401);
 assert.equal((await call('/auth',{op:'login',username:'alice',password:f.secret})).status,401);
 alice=(await call('/auth',{op:'login',username:'alice',password:'012345'})).cookie;
 const table=(await call('/api',{op:'create'},alice)).data;
 assert.equal((await call('/admin-api',{op:'revoke',userId:id},admin)).status,200);
 assert.equal((await call('/api',{op:'state',...table},alice)).status,401);
 alice=(await call('/auth',{op:'login',username:'alice',password:'012345'})).cookie;
 assert.equal((await call('/admin-api',{op:'statusChange',userId:id,status:'banned'},admin)).status,200);
 assert.equal((await call('/api',{op:'state',...table},alice)).status,401);
 assert.equal((await call('/auth',{op:'login',username:'alice',password:'012345'})).status,403);
 assert.equal((await call('/admin-api',{op:'status'},admin)).data.rooms.length,0);
 assert.equal((await call('/admin-api',{op:'statusChange',userId:state.me,status:'banned'},admin)).status,404);
 assert.equal((await call('/admin-api',{op:'statusChange',userId:status.users.find(u=>u.role==='admin').id,status:'banned'},admin)).status,400);
 assert.equal((await call('/admin-api',{op:'statusChange',userId:id,status:'active'},admin)).status,200);
 alice=(await call('/auth',{op:'login',username:'alice',password:'012345'})).cookie;
 await call('/auth',{op:'logout'},alice);assert.equal((await call('/api',{op:'create'},alice)).status,401);
 let limited=false;for(let i=0;i<16;i++){const res=await call('/auth',{op:'login',username:'unknown_account',password:f.secret});if(res.status===429){limited=true;break;}}assert(limited);
});


test('注册需要昵称和六位数字密码',async t=>{
 const f=await fixture();t.after(()=>f.close());
 for(const secret of ['12345','1234567','abcdef','12345a'])assert.equal((await f.request('/auth',{op:'register',username:'new_friend',password:secret,nickname:'朋友'})).status,400);
 assert.equal((await f.request('/auth',{op:'register',username:'new_friend',password:'123456'})).status,400);
 assert.equal((await f.request('/auth',{op:'register',username:'new_friend',password:'123456',nickname:'朋友'})).status,200);
 const login=await f.request('/auth',{op:'login',username:'new_friend',password:'123456'});assert.equal(login.status,200);
 assert.equal((await f.request('/auth',{op:'password',oldPassword:'123456',password:'12345a'},login.cookie)).status,400);
});
