const $=id=>document.getElementById(id);
const parse=(value,fallback)=>{try{return JSON.parse(value)??fallback;}catch{return fallback;}};
const deviceId=localStorage.getItem('poker-device-id')||crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
localStorage.setItem('poker-device-id',deviceId);
let session=parse(localStorage.getItem('poker-session'),null),state=null,busy=false,lastKey='',historyKey='',resultKey='',turnNoticeKey='',soundRoom='',soundHistoryLength=0,audioContext=null;
const cardBacks=['classic','ivory','midnight','ink'];
const cleanCardBack=value=>cardBacks.includes(value)?value:'classic';
const settings={sound:true,voice:true,volume:60,vibration:false,cardBack:'classic',...parse(localStorage.getItem('poker-settings'),{})};
settings.cardBack=cleanCardBack(settings.cardBack);
const voiceTexts={check:'过牌',call:'跟注',raise:'加注',allin:'全下，All in',fold:'弃牌'};
const phases={waiting:'等待朋友入座',preflop:'翻牌前',flop:'翻牌',turn:'转牌',river:'河牌',done:'本手结束'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(c,cardBack='classic'){if(c===undefined)return '<span class="card empty">·</span>';if(c===-1)return `<span class="card back skin-${cleanCardBack(cardBack)}" aria-label="隐藏牌，${cleanCardBack(cardBack)} 卡背">·</span>`;let rank=c%13+2,suit=Math.floor(c/13);return `<span class="card ${suit===1||suit===2?'red':''}" aria-label="${['黑桃','红桃','方块','梅花'][suit]}${rank}">${({11:'J',12:'Q',13:'K',14:'A'})[rank]||rank}<small>${['♠','♥','♦','♣'][suit]}</small></span>`;}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,4500);}
function save(){if(session)localStorage.setItem('poker-session',JSON.stringify(session));else localStorage.removeItem('poker-session');}
function saveSettings(){localStorage.setItem('poker-settings',JSON.stringify(settings));}
async function api(op,extra={}){const res=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,deviceId,op,...extra})});const data=await res.json();if(!res.ok)throw Error(data.error);return data;}
async function enter(op){if(busy)return;busy=true;try{const name=$('nickname').value.trim();localStorage.setItem('poker-nickname',name);session=await api(op,{name,code:$('roomcode').value.trim(),cardBack:settings.cardBack});save();state=await api('state');render();if(session.recovered)toast(`已恢复到房间 ${session.code}`);}catch(e){toast(e.message);}finally{busy=false;}}
async function command(op,extra={}){if(busy)return;busy=true;try{state=await api(op,extra);render();return state;}catch(e){toast(e.message);}finally{busy=false;}}

function unlockAudio(){const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return;if(!audioContext)audioContext=new AudioCtor();if(audioContext.state==='suspended')audioContext.resume();}
function speakVoice(kind){if(!settings.voice||!voiceTexts[kind]||!window.speechSynthesis||!window.SpeechSynthesisUtterance)return false;const utterance=new SpeechSynthesisUtterance(voiceTexts[kind]),voices=speechSynthesis.getVoices();utterance.voice=voices.find(v=>/^zh[-_]CN$/i.test(v.lang)&&/female|xiaoxiao|huihui|yaoyao|tingting|sinji/i.test(v.name))||voices.find(v=>/^zh/i.test(v.lang))||null;utterance.lang='zh-CN';utterance.rate=1.08;utterance.pitch=1.02;utterance.volume=Math.min(1,settings.volume/100);speechSynthesis.cancel();speechSynthesis.speak(utterance);return true;}
function playSound(kind){if(!settings.sound||settings.volume<=0)return;try{if(speakVoice(kind))return;if(!(window.AudioContext||window.webkitAudioContext))return;unlockAudio();const patterns={check:[[520,.05,0]],call:[[420,.05,0],[560,.07,.06]],raise:[[420,.05,0],[620,.06,.06],[820,.1,.13]],allin:[[360,.06,0],[620,.08,.07],[940,.14,.16]],fold:[[310,.09,0]],turn:[[760,.08,0],[980,.12,.1]],settle:[[520,.08,0],[660,.08,.09],[820,.16,.18]]};const gain=audioContext.createGain();gain.gain.value=settings.volume/100*.16;gain.connect(audioContext.destination);for(const [freq,duration,delay] of patterns[kind]||patterns.check){const osc=audioContext.createOscillator(),tone=audioContext.createGain(),at=audioContext.currentTime+delay;osc.type='sine';osc.frequency.value=freq;tone.gain.setValueAtTime(.001,at);tone.gain.exponentialRampToValueAtTime(1,at+.012);tone.gain.exponentialRampToValueAtTime(.001,at+duration);osc.connect(tone);tone.connect(gain);osc.start(at);osc.stop(at+duration+.02);}}catch{}}
function soundForEvent(text){if(/：过牌$/.test(text))return 'check';if(/：(?:全下跟注|全下)(?:\s|$)/.test(text))return 'allin';if(/：补入/.test(text))return 'call';if(/：加注至/.test(text))return 'raise';if(/：弃牌$/.test(text))return 'fold';if(/ 获得 \d+（/.test(text))return 'settle';return '';}
function showAllIn(text){const name=text.match(/^(.+?)：(?:全下跟注|全下)/)?.[1],player=state.players.find(p=>p.name===name),seat=[...document.querySelectorAll('.seat')].find(x=>x.dataset.playerId===player?.id);if(!seat)return;const burst=document.createElement('div');burst.className='all-in-burst';burst.textContent='ALL IN';seat.classList.remove('all-in-animate');void seat.offsetWidth;seat.classList.add('all-in-animate');seat.appendChild(burst);setTimeout(()=>{burst.remove();seat.classList.remove('all-in-animate');},300);}
function observeSounds(){const history=state.history||[];if(soundRoom!==state.code){soundRoom=state.code;soundHistoryLength=history.length;return;}if(history.length<soundHistoryLength){soundHistoryLength=history.length;return;}const fresh=history.slice(soundHistoryLength);soundHistoryLength=history.length;const event=[...fresh].reverse().find(e=>soundForEvent(e.text)),kind=event&&soundForEvent(event.text);if(kind){playSound(kind);if(kind==='allin')showAllIn(event.text);}}
function notifyTurn(myTurn){if(!myTurn){turnNoticeKey='';document.title='同桌 · 朋友德州扑克';return;}const key=`${state.code}-${state.hand}-${state.phase}-${state.deadline}`;document.title='轮到你了｜同桌';if(key===turnNoticeKey)return;turnNoticeKey=key;playSound('turn');if(settings.vibration&&navigator.vibrate)navigator.vibrate([120,60,120]);}

function render(){if(!state)return;$('lobby').hidden=true;$('game').hidden=false;$('code').textContent=state.code;$('hand').textContent=`第 ${state.hand} 手 · ${state.players.length}/8 人`;$('phase').textContent=phases[state.phase];$('pot').textContent=state.pot.toLocaleString();
 const idle=['waiting','done'].includes(state.phase),isHost=state.host===state.me,meIndex=state.players.findIndex(p=>p.id===state.me),myCardBack=cleanCardBack(state.players[meIndex]?.cardBack||settings.cardBack);$('board').innerHTML=Array.from({length:5},(_,i)=>card(state.board[i]===undefined&&!idle?-1:state.board[i],myCardBack)).join('');$('seats').innerHTML=state.players.map((p,i)=>`<div class="seat s${(i-meIndex+8)%8} ${i===state.turn?'active':''} ${p.folded?'folded':''} ${p.id===state.me?'me':''} ${!p.online?'offline':''} ${p.pendingKick?'pending-kick':''}" data-player-id="${esc(p.id)}"><div class="name">${i===state.dealer?'Ⓓ ':''}${esc(p.name)}${p.id===state.me?' · 你':''}${p.bot?' ♧':''}</div><div class="bet"><small>本轮下注</small> ${p.bet.toLocaleString()}</div><div class="total">本手累计 <strong>${p.total===undefined?'待更新':p.total.toLocaleString()}</strong></div><div class="status">${p.pendingKick?'本手后移出':!p.online?'暂时离线':esc((p.action||'已入座').replace(/（[^）]*）/g,'').replace(/^(补入|全下跟注|加注至|全下|小盲|大盲)\s+\d+$/,(_,a)=>a==='补入'?'跟注':a==='加注至'?'加注':a))}</div><div class="cards">${p.cards.map(c=>card(c,p.cardBack)).join('')}</div><div class="balance">剩余积分 ${p.stack.toLocaleString()}</div></div>`).join('');
 $('outcome').textContent=state.phase==='done'?'本手已结算 · 明细见行动历史':'';renderSettlement();renderHistory();
 const myTurn=state.players[state.turn]?.id===state.me;$('hostControls').hidden=!(idle&&isHost);$('manageRoom').hidden=!isHost;$('closeRoom').hidden=!isHost;$('actions').hidden=!myTurn;$('turnBanner').hidden=!myTurn;$('control').classList.toggle('your-turn',myTurn);$('turnText').textContent=idle?(state.phase==='done'?'本手已结束，准备下一手':'已入座，等待发牌'):myTurn?'轮到你了':`等待 ${state.players[state.turn]?.name||'朋友'} 行动`;
 const remain=state.expiresAt?Math.max(0,Math.ceil((state.expiresAt-Date.now())/60000)):0;$('help').textContent=idle?(isHost?`至少两人即可开始 · 房间约剩 ${remain} 分钟。`:`房主开始发牌后，将自动进入对局 · 房间约剩 ${remain} 分钟。`):'底牌只对你可见 · 加注至 = 本轮累计投入';$('start').textContent=state.phase==='done'?'开始下一手':'开始发牌';$('start').disabled=state.players.filter(p=>p.stack>0).length<2;$('addbot').disabled=state.players.length>=8;
 if(myTurn){const l=state.legal;$('call').textContent=l.call?`补 ${l.call} · 共 ${state.players[meIndex].bet+l.call}`:'过牌';$('raise').disabled=!l.raise;$('allin').disabled=!l.raise&&l.call<state.players[meIndex].stack;$('amount').min=l.min;$('amount').max=l.max;const key=`${state.hand}-${state.phase}-${state.high}`;if(key!==lastKey){$('amount').value=l.min;lastKey=key;}}
 observeSounds();notifyTurn(myTurn);renderManager();tick();}

function signed(n){return (n>0?'+':'')+n.toLocaleString();}
function renderSettlement(){const last=state.lastSettlement;if(!last)return;const mine=last.rows.find(x=>x.id===state.me),showdown=last.showdown?`<section class="showdown-panel"><div class="showdown-board"><span>公共牌</span><div class="cards">${(last.board||[]).map(card).join('')}</div></div><div class="showdown-hands">${last.rows.filter(x=>x.cards?.length).map(x=>`<div class="showdown-player ${x.winner?'winner':''}"><strong>${esc(x.name)}${x.id===state.me?' · 你':''}</strong><div class="cards">${x.cards.map(card).join('')}</div><span>${esc(x.label)}${x.winner?' · 获胜':''}</span></div>`).join('')}</div></section>`:'<p class="no-showdown">其他玩家均已弃牌，本手无需比牌。</p>';
 const content=last.rows.map(x=>`<div class="result-row ${x.net>0?'won':x.net<0?'lost':'even'}"><div><strong>${esc(x.name)}${x.id===state.me?' · 你':''}</strong><small>${esc(x.label)}</small></div><div class="result-net">${x.net>0?'净赢':x.net<0?'净输':'持平'} ${signed(x.net)}</div><div class="result-detail">投入 ${x.invested.toLocaleString()} · 收回 ${x.received.toLocaleString()}</div></div>`).join('');const key=state.code+'-'+last.hand;if(resultKey!==key){resultKey=key;$('resultTitle').textContent=mine?(mine.net>0?'本手获胜':mine.net<0?'本手净输':'本手持平'):'本手结算';$('resultSummary').textContent=mine?`净${mine.net>0?'赢':mine.net<0?'输':'变动'} ${Math.abs(mine.net).toLocaleString()} 积分 · 投入 ${mine.invested.toLocaleString()} · 收回 ${mine.received.toLocaleString()}`:'你未参与本手牌';$('showdown').innerHTML=showdown;$('resultRows').innerHTML=content;if(state.phase==='done'&&!$('resultDialog').open)$('resultDialog').showModal();}}
function tick(){const active=state&&!['waiting','done'].includes(state.phase),seconds=active?Math.max(0,Math.ceil((state.deadline-Date.now())/1000)):0;$('timer').textContent=active?`${seconds} 秒`:'';$('timer').classList.toggle('warning',seconds>5&&seconds<=10);$('timer').classList.toggle('critical',seconds<=5&&active);}
const run=fn=>async()=>{try{unlockAudio();await fn();}catch(e){toast(e.message);}};

function renderManager(){if(!state)return;const isHost=state.host===state.me;$('playerManager').innerHTML=state.players.map(p=>`<div class="manager-row"><div><strong>${esc(p.name)}${p.id===state.host?' · 房主':''}</strong><small>${p.bot?'人机陪练':p.online?'在线':'暂时离线'} · ${p.stack.toLocaleString()} 积分${p.pendingKick?' · 本手后移出':''}</small></div>${isHost&&p.id!==state.host?`<button class="danger kick-player" data-id="${p.id}" data-name="${esc(p.name)}" ${p.pendingKick?'disabled':''}>${p.pendingKick?'等待移出':'移出房间'}</button>`:''}</div>`).join('');for(const button of document.querySelectorAll('.kick-player'))button.onclick=run(async()=>{const during=!['waiting','done'].includes(state.phase),name=button.dataset.name;if(!confirm(during?`确定在本手结束后移出 ${name} 吗？`:`确定将 ${name} 移出房间吗？`))return;await command('kick',{playerId:button.dataset.id});toast(during?'已标记为本手结束后移出':'玩家已移出房间');});}

$('create').onclick=()=>enter('create');$('join').onclick=()=>enter('join');$('practice').onclick=run(async()=>{await enter('create');if(session){await command('bot');await command('bot');await command('start');}});
$('addbot').onclick=()=>command('bot');$('start').onclick=()=>command('start');$('reset').onclick=()=>{if(confirm('将全桌积分重置为每人 2,000？'))command('reset');};$('fold').onclick=()=>command('act',{type:'fold'});$('call').onclick=()=>command('act',{type:'call'});$('raise').onclick=()=>command('act',{type:'raise',amount:Number($('amount').value)});$('allin').onclick=()=>command('act',state.legal.raise?{type:'raise',amount:state.legal.max}:{type:'call'});
$('closeRoom').onclick=run(async()=>{if(!confirm('确定关闭房间？所有玩家会立即退出，当前对局无法恢复。'))return;await api('close');session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;toast('房间已关闭');});
$('leave').onclick=run(async()=>{await api('leave');session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;});
$('copy').onclick=run(async()=>{const invitation=`同桌朋友局\n游戏地址：${location.origin}/\n房间号：${state.code}\n打开网址，输入昵称和房间号即可加入。`;try{await navigator.clipboard.writeText(invitation);toast('邀请已复制');}catch{prompt('复制这段邀请给朋友',invitation);}});
$('rulesButton').onclick=()=>$('rules').showModal();$('closeRules').onclick=()=>$('rules').close();$('manageRoom').onclick=()=>{renderManager();$('manageDialog').showModal();};$('closeManage').onclick=()=>$('manageDialog').close();

function syncSettings(){settings.sound=!!$('soundEnabled').checked;settings.voice=!!$('voiceEnabled').checked;settings.volume=Number($('soundVolume').value);settings.vibration=!!$('vibrationEnabled').checked;$('volumeValue').textContent=`${settings.volume}%`;$('soundVolume').disabled=!settings.sound;$('voiceEnabled').disabled=!settings.sound;saveSettings();}
function renderSkinPicker(){for(const button of document.querySelectorAll('.skin-option')){const selected=button.dataset.skin===settings.cardBack;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));}}
$('settingsButton').onclick=()=>{unlockAudio();$('soundEnabled').checked=settings.sound;$('voiceEnabled').checked=settings.voice;$('soundVolume').value=settings.volume;$('volumeValue').textContent=`${settings.volume}%`;$('vibrationEnabled').checked=settings.vibration;$('vibrationEnabled').disabled=!navigator.vibrate;$('vibrationHelp').textContent=navigator.vibrate?'仅在支持震动的设备上生效':'当前浏览器不支持震动';$('soundVolume').disabled=!settings.sound;$('voiceEnabled').disabled=!settings.sound;renderSkinPicker();$('settingsDialog').showModal();};$('closeSettings').onclick=()=>$('settingsDialog').close();$('soundEnabled').onchange=syncSettings;$('voiceEnabled').onchange=syncSettings;$('soundVolume').oninput=syncSettings;$('vibrationEnabled').onchange=syncSettings;for(const button of document.querySelectorAll('.skin-option'))button.onclick=run(async()=>{settings.cardBack=cleanCardBack(button.dataset.skin);saveSettings();renderSkinPicker();if(session)await command('skin',{cardBack:settings.cardBack});toast(`已使用${button.dataset.name}卡背`);});

const historyExpanded=new Map();
function renderHistory(){const entries=state.history||[],key=JSON.stringify([state.code,state.hand,state.phase,entries]);if(key===historyKey)return;historyKey=key;const panel=$('logs'),scroll=panel.scrollTop,groups=new Map();for(const e of entries){if(!groups.has(e.hand))groups.set(e.hand,[]);groups.get(e.hand).push(e);}panel.innerHTML=groups.size?[...groups].reverse().map(([hand,events])=>{const ended=events.some(e=>e.phase==='done'),groupKey=state.code+'-'+hand+'-'+(ended?'done':'playing'),expanded=historyExpanded.has(groupKey)?historyExpanded.get(groupKey):!ended&&hand===state.hand;return `<details data-key="${groupKey}" ${expanded?'open':''}><summary>第 ${hand} 手 · ${ended?'已结算':hand===state.hand?'进行中':'记录'}</summary>${events.map((e,i)=>`${i===0||events[i-1].phase!==e.phase?`<h4>${esc(phases[e.phase]||e.phase)}</h4>`:''}<div class="history-event"><time>${new Date(e.time).toLocaleTimeString('zh-CN',{hour12:false})}</time><span>${esc(e.text)}</span></div>`).join('')}</details>`;}).join(''):'<p>发牌后会记录盲注、行动、公共牌和结算。保留最近 30 手。</p>';for(const details of panel.querySelectorAll('details'))details.addEventListener('toggle',()=>{if(details.isConnected)historyExpanded.set(details.dataset.key,details.open);});panel.scrollTop=scroll;}
async function poll(){if(!session||busy)return;try{state=await api('state');render();}catch(e){if(/房间不存在|身份已失效|5 小时上限/.test(e.message)){session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;document.title='同桌 · 朋友德州扑克';}toast(/身份已失效/.test(e.message)?'你已离开或被房主移出房间':'连接中断：'+e.message);}}
setInterval(poll,1000);setInterval(tick,250);$('nickname').value=localStorage.getItem('poker-nickname')||'玩家';poll();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_poker_table',description:'读取当前玩家可见的牌桌状态，不包含其他玩家隐藏底牌。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{if(!session)throw Error('尚未加入房间');await poll();return state;}})).catch(()=>{});}catch{}}
$('closeResult').onclick=()=>$('resultDialog').close();
