import {VoiceManager} from '/voice-manager.js';
const $=id=>document.getElementById(id);
const parse=(value,fallback)=>{try{return JSON.parse(value)??fallback;}catch{return fallback;}};
const deviceId=localStorage.getItem('poker-device-id')||crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
localStorage.setItem('poker-device-id',deviceId);
let commandRevision=0,accountGeneration=0,session=parse(localStorage.getItem('poker-session'),null),state=null,busy=false,lastKey='',historyKey='',resultKey='',turnNoticeKey='',soundRoom='',soundHistoryLength=0;
const cardBacks=['classic','ivory','midnight','ink'];
const cleanCardBack=value=>cardBacks.includes(value)?value:'classic';
const settings={sound:true,voice:true,volume:60,vibration:false,...parse(localStorage.getItem('poker-settings'),{})};
delete settings.cardBack;
const voiceFiles={check:'check.mp3',call:'call.mp3',raise:'raise.mp3',allin:'all_in.mp3',fold:'fold.mp3',turn:'your_turn.mp3',settle:'showdown.mp3'};
const voiceOffsets={check:.18,call:.18,raise:.18,allin:.18,fold:.30,turn:.18,settle:.20};
const voiceAudio=Object.fromEntries(Object.entries(voiceFiles).map(([kind,file])=>{const audio=new Audio(`/audio/voice/${file}`);audio.preload='auto';audio.load();return [kind,audio];}));
const phases={waiting:'等待朋友入座',preflop:'翻牌前',flop:'翻牌',turn:'转牌',river:'河牌',done:'本手结束'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(c,cardBack='classic'){if(c===undefined)return '<span class="card empty">·</span>';if(c===-1)return `<span class="card back skin-${cleanCardBack(cardBack)}" aria-label="隐藏牌，${cleanCardBack(cardBack)} 卡背">·</span>`;let rank=c%13+2,suit=Math.floor(c/13);return `<span class="card ${suit===1||suit===2?'red':''}" aria-label="${['黑桃','红桃','方块','梅花'][suit]}${rank}">${({11:'J',12:'Q',13:'K',14:'A'})[rank]||rank}<small>${['♠','♥','♦','♣'][suit]}</small></span>`;}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,4500);}
function save(){if(session)localStorage.setItem('poker-session',JSON.stringify(session));else localStorage.removeItem('poker-session');}
function saveSettings(){localStorage.setItem('poker-settings',JSON.stringify(settings));}
async function api(op,extra={}){const generation=accountGeneration,res=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,deviceId,op,...extra})});const data=await res.json();if(generation!==accountGeneration)throw Error('账号已切换');if(!res.ok){if(res.status===401||res.status===403)window.dispatchEvent(new Event('poker-auth-expired'));throw Error(data.error);}return data;}
async function enter(op){if(busy)return false;busy=true;try{session=await api(op,{code:$('roomcode').value.trim()});save();state=await api('state');render();if(session.recovered)toast(`已恢复到房间 ${session.code}`);return true;}catch(e){toast(e.message);return false;}finally{busy=false;}}
async function command(op,extra={}){if(busy)return;commandRevision++;busy=true;if(op==='act'){voice.stop();}try{state=await api(op,extra);render();return state;}catch(e){toast(e.message);}finally{busy=false;}}

function unlockAudio(){for(const audio of Object.values(voiceAudio))audio.load();}
const voice=new VoiceManager({audio:kind=>voiceAudio[kind],offset:kind=>voiceOffsets[kind]||0,enabled:()=>settings.sound&&settings.voice&&settings.volume>0&&!document.hidden,volume:()=>Math.min(1,settings.volume/100),debug:(...args)=>{if(localStorage.getItem('poker-voice-debug')==='1')console.debug(...args);}});
const voiceContext=()=>state?`${state.code}:${state.hand}:${state.phase}:${state.turn}:${state.deadline}:${state.history?.at(-1)?.eventId||''}`:'';
let voiceSequence=0;
function soundForEvent(text){if(/：过牌$/.test(text))return 'check';if(/：(?:全下跟注|全下)(?:\s|$)/.test(text))return 'allin';if(/：补入/.test(text))return 'call';if(/：加注至/.test(text))return 'raise';if(/：弃牌$/.test(text))return 'fold';if(/ 获得 \d+（/.test(text))return 'settle';return '';}
function showAllIn(text){const name=text.match(/^(.+?)：(?:全下跟注|全下)/)?.[1],player=state.players.find(p=>p.name===name),seat=[...document.querySelectorAll('.seat')].find(x=>x.dataset.playerId===player?.id),table=document.querySelector('.table-wrap');if(!seat||!table)return;table.querySelector('.all-in-burst')?.remove();const burst=document.createElement('div');burst.className='all-in-burst';burst.textContent='ALL IN';seat.classList.remove('all-in-animate');void seat.offsetWidth;seat.classList.add('all-in-animate');table.appendChild(burst);setTimeout(()=>{burst.remove();seat.classList.remove('all-in-animate');},1000);}
function observeSounds(){
 const history=state.history||[],latest=history.at(-1)?.sequence||0,context=voiceContext();voice.update(context);
 if(soundRoom!==state.code){soundRoom=state.code;voiceSequence=latest;return;}
 if(latest<=voiceSequence)return;
 const fresh=history.filter(e=>e.sequence>voiceSequence);voiceSequence=latest;
 const event=[...fresh].reverse().find(e=>soundForEvent(e.text));
 if(!event||event.hand!==state.hand||Date.now()-event.time>2500)return;
 const kind=soundForEvent(event.text);voice.play(event.eventId,kind,context,()=>voiceContext()===context&&Date.now()-event.time<5000);
 if(kind==='allin')showAllIn(event.text);
}
function notifyTurn(myTurn){
 if(!myTurn){turnNoticeKey='';document.title='同桌 · 朋友德州扑克';return;}
 const context=voiceContext(),key=`turn:${context}`;document.title='轮到你了｜同桌';
 if(key===turnNoticeKey)return;turnNoticeKey=key;
 voice.turn(key,context,()=>voiceContext()===context&&state?.players[state.turn]?.id===state.me&&Date.now()<state.deadline);
 if(settings.vibration&&navigator.vibrate)navigator.vibrate([120,60,120]);
}
function suggestedRaise(fraction){const me=state?.players.find(p=>p.id===state.me),l=state?.legal;if(!me||!l?.raise)return null;const potAfterCall=state.pot+l.call;const raw=me.bet+l.call+potAfterCall*fraction;const rounded=Math.round(raw/10)*10;return Math.max(l.min,Math.min(l.max,rounded));}
function updatePotPresets(myTurn){for(const button of document.querySelectorAll('[data-pot]')){const amount=myTurn?suggestedRaise(Number(button.dataset.pot)):null;button.disabled=amount===null;button.title=amount===null?'当前不能加注':`填入加注至 ${amount.toLocaleString()}`;}}
function refillTier(p){return p.refillCount>=3?['refill-abyss','深渊']:p.refillCount===2?['refill-debt','负债']:p.refillCount===1?['refill-life','续命']:['',''];}

function render(){if(!state)return;$('lobby').hidden=true;$('game').hidden=false;$('logout').hidden=true;$('code').textContent=state.code;$('hand').textContent=`第 ${state.hand} 手 · ${state.players.length}/8 人`;$('phase').textContent=phases[state.phase];$('pot').textContent=state.pot.toLocaleString();
 const idle=['waiting','done'].includes(state.phase),isHost=state.host===state.me,meIndex=state.players.findIndex(p=>p.id===state.me),me=state.players[meIndex],isSpectator=!idle&&!me?.inHand,myCardBack=cleanCardBack(me?.cardBack);$('board').innerHTML=Array.from({length:5},(_,i)=>card(state.board[i]===undefined&&!idle?-1:state.board[i],myCardBack)).join('');$('seats').innerHTML=state.players.map((p,i)=>{const [refillClass,refillLabel]=refillTier(p),status=p.pendingKick?'本手后移出':p.refillPending?'等待补分审批':!p.online?'暂时离线':p.stack===0&&idle?'积分归零':(p.action||'已入座').replace(/（[^）]*）/g,'').replace(/^(补入|全下跟注|加注至|全下|小盲|大盲)\s+\d+$/,(_,a)=>a==='补入'?'跟注':a==='加注至'?'加注':a);return `<div class="seat s${(i-meIndex+8)%8} ${i===state.turn?'active':''} ${p.folded?'folded':''} ${p.id===state.me?'me':''} ${!p.online?'offline':''} ${p.pendingKick?'pending-kick':''} ${refillClass}" data-player-id="${esc(p.id)}">${refillLabel?`<span class="refill-badge">${refillLabel}</span>`:''}<div class="name">${i===state.dealer?'Ⓓ ':''}${esc(p.name)}${p.id===state.me?' · 你':''}${p.bot?' ♧':''}</div><div class="bet"><small>本手</small> ${p.bet.toLocaleString()}</div><div class="total">本手累计 <strong>${p.total===undefined?'待更新':p.total.toLocaleString()}</strong></div><div class="status">${esc(status)}</div><div class="cards">${p.cards.map(c=>card(c,p.cardBack)).join('')}</div><div class="balance">积分：${p.stack.toLocaleString()}</div></div>`;}).join('');
 $('outcome').textContent=state.phase==='done'?'本手已结算 · 明细见行动历史':'';renderSettlement();renderHistory();
 const myTurn=state.players[state.turn]?.id===state.me,pendingRefills=state.players.filter(p=>p.refillPending).length;$('hostControls').hidden=!(idle&&isHost);$('refillControls').hidden=!(idle&&me?.stack===0&&!me.bot);$('requestRefill').hidden=!!me?.refillPending;$('refillStatus').textContent=me?.refillPending?'已申请，等待房主处理':'补分会保留累计负战绩';$('manageRoom').hidden=!isHost;$('manageRoom').textContent=pendingRefills?`房间管理 (${pendingRefills})`:'房间管理';$('closeRoom').hidden=!isHost;$('actions').hidden=!myTurn;$('turnBanner').hidden=!myTurn;$('control').classList.toggle('your-turn',myTurn);$('turnText').textContent=idle?(me?.refillPending?'补分申请等待房主处理':me?.stack===0?'积分已归零，可申请补分':state.phase==='done'?'本手已结束，准备下一手':'已入座，等待发牌'):isSpectator?'正在观战 · 下一手自动入座':myTurn?'轮到你了':`等待 ${state.players[state.turn]?.name||'朋友'} 行动`;
 const remain=state.expiresAt?Math.max(0,Math.ceil((state.expiresAt-Date.now())/60000)):0;$('help').textContent=idle?(isHost?`至少两人即可开始 · 房间约剩 ${remain} 分钟。`:`房主开始发牌后，将自动进入对局 · 房间约剩 ${remain} 分钟。`):isSpectator?'当前手可观看公共牌和行动，下一手开始时自动获得座位和底牌。':'底牌只对你可见 · 加注至 = 本轮累计投入';$('start').textContent=state.phase==='done'?'开始下一手':'开始发牌';$('start').disabled=state.players.filter(p=>p.stack>0).length<2;$('addbot').disabled=state.players.length>=8;
 if(myTurn){const l=state.legal;$('call').textContent=l.call?`补 ${l.call} · 共 ${state.players[meIndex].bet+l.call}`:'过牌';$('raise').disabled=!l.raise;$('allin').disabled=!l.raise&&l.call<state.players[meIndex].stack;$('amount').min=l.min;$('amount').max=l.max;const key=`${state.hand}-${state.phase}-${state.high}`;if(key!==lastKey){$('amount').value=l.min;lastKey=key;}}
 updatePotPresets(myTurn);observeSounds();notifyTurn(myTurn);renderManager();tick();}

function signed(n){return (n>0?'+':'')+n.toLocaleString();}
function renderSettlement(){const last=state.lastSettlement;if(!last)return;const mine=last.rows.find(x=>x.id===state.me),showdown=last.showdown?`<section class="showdown-panel"><div class="showdown-board"><span>公共牌</span><div class="cards">${(last.board||[]).map(card).join('')}</div></div><div class="showdown-hands">${last.rows.filter(x=>x.cards?.length).map(x=>`<div class="showdown-player ${x.winner?'winner':''}"><strong>${esc(x.name)}${x.id===state.me?' · 你':''}</strong><div class="cards">${x.cards.map(card).join('')}</div><span>${esc(x.label)}${x.winner?' · 获胜':''}</span></div>`).join('')}</div></section>`:'<p class="no-showdown">其他玩家均已弃牌，本手无需比牌。</p>';
 const content=last.rows.map(x=>`<div class="result-row ${x.net>0?'won':x.net<0?'lost':'even'}"><div><strong>${esc(x.name)}${x.id===state.me?' · 你':''}</strong><small>${esc(x.label)}</small></div><div class="result-net">${x.net>0?'净赢':x.net<0?'净输':'持平'} ${signed(x.net)}</div><div class="result-detail">投入 ${x.invested.toLocaleString()} · 收回 ${x.received.toLocaleString()}</div></div>`).join('');const key=state.code+'-'+last.hand;if(resultKey!==key){resultKey=key;$('resultTitle').textContent=mine?(mine.net>0?'本手获胜':mine.net<0?'本手净输':'本手持平'):'本手结算';$('resultSummary').textContent=mine?`净${mine.net>0?'赢':mine.net<0?'输':'变动'} ${Math.abs(mine.net).toLocaleString()} 积分 · 投入 ${mine.invested.toLocaleString()} · 收回 ${mine.received.toLocaleString()}`:'你未参与本手牌';$('showdown').innerHTML=showdown;$('resultRows').innerHTML=content;if(state.phase==='done'&&!$('resultDialog').open)$('resultDialog').showModal();}}
function tick(){const active=state&&!['waiting','done'].includes(state.phase),seconds=active?Math.max(0,Math.ceil((state.deadline-Date.now())/1000)):0;$('timer').textContent=active?`${seconds} 秒`:'';$('timer').classList.toggle('warning',seconds>5&&seconds<=10);$('timer').classList.toggle('critical',seconds<=5&&active);}
const run=fn=>async()=>{try{unlockAudio();await fn();}catch(e){toast(e.message);}};

function renderManager(){if(!state)return;const isHost=state.host===state.me;$('playerManager').innerHTML=state.players.map(p=>`<div class="manager-row"><div><strong>${esc(p.name)}${p.id===state.host?' · 房主':''}</strong><small>${p.bot?'人机陪练':p.online?'在线':'暂时离线'} · ${p.stack.toLocaleString()} 积分 · 累计战绩 ${signed(p.record||0)}${p.refillCount?` · 补分 ${p.refillCount} 次`:''}${p.refillPending?' · 等待补分审批':''}${p.pendingKick?' · 本手后移出':''}</small></div><div class="manager-actions">${isHost&&p.refillPending?`<button class="primary refill-response" data-id="${p.id}" data-approved="true">批准补分</button><button class="quiet refill-response" data-id="${p.id}" data-approved="false">拒绝</button>`:''}${isHost&&p.id!==state.host?`<button class="danger kick-player" data-id="${p.id}" data-name="${esc(p.name)}" ${p.pendingKick?'disabled':''}>${p.pendingKick?'等待移出':'移出房间'}</button>`:''}</div></div>`).join('');for(const button of document.querySelectorAll('.refill-response'))button.onclick=run(async()=>{const result=await command('refillRespond',{playerId:button.dataset.id,approved:button.dataset.approved==='true'});if(result)toast(button.dataset.approved==='true'?'补分已批准':'补分申请已拒绝');});for(const button of document.querySelectorAll('.kick-player'))button.onclick=run(async()=>{const during=!['waiting','done'].includes(state.phase),name=button.dataset.name;if(!confirm(during?`确定在本手结束后移出 ${name} 吗？`:`确定将 ${name} 移出房间吗？`))return;await command('kick',{playerId:button.dataset.id});toast(during?'已标记为本手结束后移出':'玩家已移出房间');});}

$('create').onclick=()=>enter('create');$('join').onclick=()=>enter('join');$('practice').onclick=run(async()=>{if(await enter('create')){await command('bot');await command('bot');await command('start');}});
$('addbot').onclick=()=>command('bot');$('start').onclick=()=>command('start');$('reset').onclick=()=>{if(confirm('将全桌积分重置为每人 2,000？'))command('reset');};$('fold').onclick=()=>command('act',{type:'fold'});$('call').onclick=()=>command('act',{type:'call'});$('raise').onclick=()=>command('act',{type:'raise',amount:Number($('amount').value)});$('allin').onclick=()=>command('act',state.legal.raise?{type:'raise',amount:state.legal.max}:{type:'call'});
$('requestRefill').onclick=run(async()=>{const result=await command('refillRequest');if(result)toast('补分申请已提交');});
for(const button of document.querySelectorAll('[data-pot]'))button.onclick=()=>{const amount=suggestedRaise(Number(button.dataset.pot));if(amount!==null){$('amount').value=amount;$('amount').focus();}};
$('closeRoom').onclick=run(async()=>{if(!confirm('确定关闭房间？所有玩家会立即退出，当前对局无法恢复。'))return;await api('close');voice.stop();session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;$('logout').hidden=false;toast('房间已关闭');});
$('leave').onclick=run(async()=>{await api('leave');voice.stop();session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;$('logout').hidden=false;});
$('copy').onclick=run(async()=>{const url=new URL('/',location.origin);url.searchParams.set('room',state.code);const invitation=`同桌朋友局\n游戏地址：${url.href}\n房间号：${state.code}\n请先登录已获房主批准的账号。`;try{await navigator.clipboard.writeText(invitation);toast('邀请已复制');}catch{prompt('复制这段邀请给朋友',invitation);}});
$('rulesButton').onclick=()=>$('rules').showModal();$('closeRules').onclick=()=>$('rules').close();$('manageRoom').onclick=()=>{renderManager();$('manageDialog').showModal();};$('closeManage').onclick=()=>$('manageDialog').close();

function syncSettings(){settings.sound=!!$('soundEnabled').checked;settings.voice=!!$('voiceEnabled').checked;settings.volume=Number($('soundVolume').value);settings.vibration=!!$('vibrationEnabled').checked;$('volumeValue').textContent=`${settings.volume}%`;$('soundVolume').disabled=!settings.sound;$('voiceEnabled').disabled=!settings.sound;saveSettings();voice.update(voiceContext());}
$('settingsButton').onclick=()=>{unlockAudio();$('soundEnabled').checked=settings.sound;$('voiceEnabled').checked=settings.voice;$('soundVolume').value=settings.volume;$('volumeValue').textContent=`${settings.volume}%`;$('vibrationEnabled').checked=settings.vibration;$('vibrationEnabled').disabled=!navigator.vibrate;$('vibrationHelp').textContent=navigator.vibrate?'仅在支持震动的设备上生效':'当前浏览器不支持震动';$('soundVolume').disabled=!settings.sound;$('voiceEnabled').disabled=!settings.sound;$('settingsDialog').showModal();};$('closeSettings').onclick=()=>$('settingsDialog').close();$('soundEnabled').onchange=syncSettings;$('voiceEnabled').onchange=syncSettings;$('soundVolume').oninput=syncSettings;$('vibrationEnabled').onchange=syncSettings;

const historyExpanded=new Map();
function renderHistory(){const entries=state.history||[],key=JSON.stringify([state.code,state.hand,state.phase,entries]);if(key===historyKey)return;historyKey=key;const panel=$('logs'),scroll=panel.scrollTop,groups=new Map();for(const e of entries){if(!groups.has(e.hand))groups.set(e.hand,[]);groups.get(e.hand).push(e);}panel.innerHTML=groups.size?[...groups].reverse().map(([hand,events])=>{const ended=events.some(e=>e.phase==='done'),groupKey=state.code+'-'+hand+'-'+(ended?'done':'playing'),expanded=historyExpanded.has(groupKey)?historyExpanded.get(groupKey):!ended&&hand===state.hand;return `<details data-key="${groupKey}" ${expanded?'open':''}><summary>第 ${hand} 手 · ${ended?'已结算':hand===state.hand?'进行中':'记录'}</summary>${events.map((e,i)=>`${i===0||events[i-1].phase!==e.phase?`<h4>${esc(phases[e.phase]||e.phase)}</h4>`:''}<div class="history-event"><time>${new Date(e.time).toLocaleTimeString('zh-CN',{hour12:false})}</time><span>${esc(e.text)}</span></div>`).join('')}</details>`;}).join(''):'<p>发牌后会记录盲注、行动、公共牌和结算。保留最近 30 手。</p>';for(const details of panel.querySelectorAll('details'))details.addEventListener('toggle',()=>{if(details.isConnected)historyExpanded.set(details.dataset.key,details.open);});panel.scrollTop=scroll;}
async function poll(){if(!session||busy||poll.pending)return;const activeSession=session,revision=commandRevision;poll.pending=true;try{const next=await api('state');if(session!==activeSession||revision!==commandRevision)return;state=next;render();}catch(e){if(session!==activeSession)return;if(/房间不存在|身份已失效|5 小时上限/.test(e.message)){voice.stop();session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;$('logout').hidden=false;document.title='同桌 · 朋友德州扑克';}toast(/身份已失效/.test(e.message)?'你已离开或被房主移出房间':'连接中断：'+e.message);}finally{poll.pending=false;}}
setInterval(poll,250);setInterval(tick,250);const invitedRoom=new URLSearchParams(location.search).get('room');if(/^\d{6}$/.test(invitedRoom||''))$('roomcode').value=invitedRoom;$('lobby').hidden=!!session;poll();
window.addEventListener('poker-account-cleared',()=>{accountGeneration++;voice.stop();session=null;state=null;save();$('game').hidden=true;historyKey='';resultKey='';document.title='同桌 · 朋友德州扑克';});
window.addEventListener('poker-account-ready',()=>{session=parse(localStorage.getItem('poker-session'),null);$('lobby').hidden=!!session;$('logout').hidden=!!session;if(session)poll();});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_poker_table',description:'读取当前玩家可见的牌桌状态，不包含其他玩家隐藏底牌。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{if(!session)throw Error('尚未加入房间');await poll();return state;}})).catch(()=>{});}catch{}}
$('closeResult').onclick=()=>$('resultDialog').close();

window.pokerJoinRoom=async code=>{$('roomcode').value=code;return enter('join');};
import('/community-ui.js');

document.addEventListener('visibilitychange',()=>{if(document.hidden)voice.stop();});
