const $=id=>document.getElementById(id);let session=JSON.parse(sessionStorage.getItem('poker-session')||'null'),state=null,busy=false,lastKey='',historyKey='',resultKey='';
const phases={waiting:'等待朋友入座',preflop:'翻牌前',flop:'翻牌',turn:'转牌',river:'河牌',done:'本手结束'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(c){if(c===undefined)return '<span class="card empty">·</span>';if(c===-1)return '<span class="card back" aria-label="隐藏底牌">·</span>';let rank=c%13+2,suit=Math.floor(c/13);return `<span class="card ${suit===1||suit===2?'red':''}" aria-label="${['黑桃','红桃','方块','梅花'][suit]}${rank}">${({11:'J',12:'Q',13:'K',14:'A'})[rank]||rank}<small>${['♠','♥','♦','♣'][suit]}</small></span>`;}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,4500);}
async function api(op,extra={}){const res=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,op,...extra})});const data=await res.json();if(!res.ok)throw Error(data.error);return data;}
function save(){if(session)sessionStorage.setItem('poker-session',JSON.stringify(session));else sessionStorage.removeItem('poker-session');}
async function enter(op){if(busy)return;busy=true;try{session=await api(op,{name:$('nickname').value,code:$('roomcode').value.trim()});save();state=await api('state');render();}catch(e){toast(e.message);}finally{busy=false;}}
async function command(op,extra={}){if(busy)return;busy=true;try{state=await api(op,extra);render();}catch(e){toast(e.message);}finally{busy=false;}}
function render(){if(!state)return;$('lobby').hidden=true;$('game').hidden=false;$('code').textContent=state.code;$('hand').textContent=`第 ${state.hand} 手 · ${state.players.length}/6 人`;$('phase').textContent=phases[state.phase];$('pot').textContent=state.pot.toLocaleString();$('board').innerHTML=Array.from({length:5},(_,i)=>card(state.board[i])).join('');
 const meIndex=state.players.findIndex(p=>p.id===state.me);$('seats').innerHTML=state.players.map((p,i)=>`<div class="seat s${(i-meIndex+6)%6} ${i===state.turn?'active':''} ${p.folded?'folded':''}"><div class="name">${i===state.dealer?'Ⓓ ':''}${esc(p.name)}${p.id===state.me?' · 你':''}${p.bot?' ♧':''}</div><div class="bet"><small>本轮下注</small> ${p.bet.toLocaleString()}</div><div class="total">本手累计 <strong>${p.total===undefined?'待更新':p.total.toLocaleString()}</strong></div><div class="status">${esc((p.action||'已入座').replace(/（[^）]*）/g,'').replace(/^(补入|全下跟注|加注至|全下|小盲|大盲)\s+\d+$/,(_,a)=>a==='补入'?'跟注':a==='加注至'?'加注':a))}</div><div class="cards">${p.cards.map(card).join('')}</div><div class="balance">剩余积分 ${p.stack.toLocaleString()}</div></div>`).join('');
 $('outcome').textContent=state.phase==='done'?'本手已结算 · 明细见行动历史':'';renderSettlement();renderHistory();
 const idle=['waiting','done'].includes(state.phase),myTurn=state.players[state.turn]?.id===state.me;$('hostControls').hidden=!(idle&&state.host===state.me);$('actions').hidden=!myTurn;$('turnText').textContent=idle?(state.phase==='done'?'本手已结束，准备下一手':'已入座，等待发牌'):myTurn?'轮到你行动':`等待 ${state.players[state.turn]?.name||'朋友'} 行动`;
 $('help').textContent=idle?(state.host===state.me?'至少两人即可开始。朋友未到时，可以添加陪练。':'房主开始发牌后，将自动进入对局。'):'底牌只对你可见 · 加注至 = 本轮累计投入';$('start').textContent=state.phase==='done'?'开始下一手':'开始发牌';$('start').disabled=state.players.filter(p=>p.stack>0).length<2;$('addbot').disabled=state.players.length>=6;
 if(myTurn){const l=state.legal;$('call').textContent=l.call?`补 ${l.call} · 共 ${state.players[meIndex].bet+l.call}`:'过牌';$('raise').disabled=!l.raise;$('allin').disabled=!l.raise&&l.call<state.players[meIndex].stack;$('amount').min=l.min;$('amount').max=l.max;const key=`${state.hand}-${state.phase}-${state.high}`;if(key!==lastKey){$('amount').value=l.min;lastKey=key;}}tick();}
function signed(n){return (n>0?'+':'')+n.toLocaleString();}
function renderSettlement(){const last=state.lastSettlement;if(!last)return;const mine=last.rows.find(x=>x.id===state.me);const content=last.rows.map(x=>`<div class="result-row ${x.net>0?'won':x.net<0?'lost':'even'}"><div><strong>${esc(x.name)}${x.id===state.me?' · 你':''}</strong><small>${esc(x.label)}</small></div><div class="result-net">${x.net>0?'净赢':x.net<0?'净输':'持平'} ${signed(x.net)}</div><div class="result-detail">投入 ${x.invested.toLocaleString()} · 收回 ${x.received.toLocaleString()}</div></div>`).join('');const key=state.code+'-'+last.hand;if(resultKey!==key){resultKey=key;$('resultTitle').textContent=mine?(mine.net>0?'本手获胜':mine.net<0?'本手净输':'本手持平'):'本手结算';$('resultSummary').textContent=mine?`净${mine.net>0?'赢':mine.net<0?'输':'变动'} ${Math.abs(mine.net).toLocaleString()} 积分 · 投入 ${mine.invested.toLocaleString()} · 收回 ${mine.received.toLocaleString()}`:'你未参与本手牌';$('resultRows').innerHTML=content;if(state.phase==='done'&&!$('resultDialog').open)$('resultDialog').showModal();}}
function tick(){$('timer').textContent=state&&!['waiting','done'].includes(state.phase)?`${Math.max(0,Math.ceil((state.deadline-Date.now())/1000))} 秒`:'';}
const run=fn=>async()=>{try{await fn();}catch(e){toast(e.message);}};
$('create').onclick=()=>enter('create');$('join').onclick=()=>enter('join');$('practice').onclick=run(async()=>{await enter('create');if(session){await command('bot');await command('bot');await command('start');}});
$('addbot').onclick=()=>command('bot');$('start').onclick=()=>command('start');$('reset').onclick=()=>{if(confirm('将全桌积分重置为每人 2,000？'))command('reset');};$('fold').onclick=()=>command('act',{type:'fold'});$('call').onclick=()=>command('act',{type:'call'});$('raise').onclick=()=>command('act',{type:'raise',amount:Number($('amount').value)});$('allin').onclick=()=>command('act',state.legal.raise?{type:'raise',amount:state.legal.max}:{type:'call'});
$('leave').onclick=run(async()=>{await api('leave');session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;});
$('copy').onclick=run(async()=>{const invitation=`同桌朋友局 · 房间号 ${state.code} · ${location.origin}（同一 Wi-Fi；若显示 localhost，请改用房主电脑的局域网地址）`;try{await navigator.clipboard.writeText(invitation);toast('邀请已复制');}catch{prompt('复制这段邀请给朋友',invitation);}});
$('rulesButton').onclick=()=>$('rules').showModal();$('closeRules').onclick=()=>$('rules').close();
const historyExpanded=new Map();
function renderHistory(){
 const entries=state.history||[],key=JSON.stringify([state.code,state.hand,state.phase,entries]);if(key===historyKey)return;historyKey=key;
 const panel=$('logs'),scroll=panel.scrollTop,groups=new Map();
 for(const e of entries){if(!groups.has(e.hand))groups.set(e.hand,[]);groups.get(e.hand).push(e);}
 panel.innerHTML=groups.size?[...groups].reverse().map(([hand,events])=>{
  const ended=events.some(e=>e.phase==='done'),groupKey=state.code+'-'+hand+'-'+(ended?'done':'playing');
  const expanded=historyExpanded.has(groupKey)?historyExpanded.get(groupKey):!ended&&hand===state.hand;
  return `<details data-key="${groupKey}" ${expanded?'open':''}><summary>第 ${hand} 手 · ${ended?'已结算':hand===state.hand?'进行中':'记录'}</summary>${events.map((e,i)=>`${i===0||events[i-1].phase!==e.phase?`<h4>${esc(phases[e.phase]||e.phase)}</h4>`:''}<div class="history-event"><time>${new Date(e.time).toLocaleTimeString('zh-CN',{hour12:false})}</time><span>${esc(e.text)}</span></div>`).join('')}</details>`;
 }).join(''):'<p>发牌后会记录盲注、行动、公共牌和结算。保留最近 30 手。</p>';
 for(const details of panel.querySelectorAll('details'))details.addEventListener('toggle',()=>{if(details.isConnected)historyExpanded.set(details.dataset.key,details.open);});
 panel.scrollTop=scroll;
}
async function poll(){if(!session||busy)return;try{state=await api('state');render();}catch(e){if(/房间不存在|身份已失效/.test(e.message)){session=null;state=null;save();$('game').hidden=true;$('lobby').hidden=false;}toast('连接中断：'+e.message);}}setInterval(poll,1000);setInterval(tick,250);poll();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_poker_table',description:'读取当前玩家可见的本地牌桌状态，不包含其他玩家隐藏底牌。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{if(!session)throw Error('尚未加入房间');await poll();return state;}})).catch(()=>{});}catch{}}

$('closeResult').onclick=()=>$('resultDialog').close();
