import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fixture} from './test-server.mjs';

const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/Ziran/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const f=await fixture();let browser;
await mkdir(new URL('./test-output/',import.meta.url),{recursive:true});
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const errors=[],admin=await browser.newPage({viewport:{width:1440,height:1000}}),friend=await browser.newPage({viewport:{width:390,height:900}});
 for(const page of [admin,friend]){await page.addInitScript(()=>{window.__audioTimeline=[];window.Audio=class extends EventTarget{constructor(src=''){super();this.src=src;this.volume=1;this.currentTime=0;this.timer=null;}load(){}pause(){clearTimeout(this.timer);this.timer=null;}play(){const file=this.src.split('/').pop();window.__audioTimeline.push({file,event:'start',at:performance.now()});this.timer=setTimeout(()=>{this.timer=null;window.__audioTimeline.push({file,event:'end',at:performance.now()});this.dispatchEvent(new Event('ended'));},80);return Promise.resolve();}};});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(f.base);}
 async function login(page,name,password=f.secret){await page.locator('#username').fill(name);await page.locator('#password').fill(password);await page.locator('#authSubmit').click();}
 await login(admin,'test_admin');await admin.locator('#create').waitFor({state:'visible'});
 assert(await admin.locator('#adminButton').isVisible());assert(await admin.locator('#logout').isVisible());
 assert.match(await admin.locator('#accountName').innerText(),/LV\.1[\s\S]*房主/);
 await admin.locator('#passwordButton').click();assert(!await admin.locator('#passwordDialog .skin-option').first().isVisible());assert(!await admin.locator('#settingsNickname').isVisible());assert(!await admin.locator('#oldPassword').isVisible());await admin.locator('#progressSection summary').click();assert.match(await admin.locator('#progressOverview').innerText(),/LV\.1/);assert.match(await admin.locator('#progressOverview').innerText(),/0 XP/);assert.equal(await admin.locator('#levelRules .level-rule').count(),30);await admin.locator('#skinSection summary').click();assert.equal(await admin.locator('#passwordDialog .skin-option').count(),4);assert.equal(await admin.locator('.table-skin-option').count(),4);await admin.locator('#passwordDialog .skin-option[data-skin=midnight]').click();await admin.getByText('账号已同步',{exact:false}).waitFor();await admin.locator('.table-skin-option[data-table-skin=midnight]').click();await admin.getByText('仅当前设备可见',{exact:false}).waitFor();assert.equal(await admin.locator('html').getAttribute('data-table-skin'),'midnight');await admin.locator('#closePassword').click();
 await admin.locator('#settingsButton').click();assert.equal(await admin.locator('#settingsDialog .skin-option').count(),0);await admin.locator('#closeSettings').click();
 assert(!await friend.locator('#accountNickname').isVisible());await friend.locator('#authToggle').click();
 await friend.locator('#username').fill('browser_friend');await friend.locator('#password').fill(f.secret);await friend.locator('#accountNickname').fill('浏览器朋友');await friend.locator('#authSubmit').click();
 await friend.getByText('注册成功，请等待房主确认身份并审批后登录',{exact:true}).waitFor();await login(friend,'browser_friend');await friend.locator('#pendingPanel').waitFor({state:'visible'});
 await admin.locator('#adminButton').click();assert(!await admin.locator('#adminUsers').isVisible());assert(!await admin.locator('#adminAudit').isVisible());await admin.locator('#adminUsersSection summary').click();await admin.locator('.admin-user').filter({hasText:'browser_friend'}).getByRole('button',{name:'批准',exact:true}).click();await admin.locator('.admin-user').filter({hasText:'browser_friend'}).getByText('已批准',{exact:false}).waitFor();
 await friend.locator('#refreshApproval').click();await friend.locator('#create').waitFor({state:'visible'});
 assert(!await friend.locator('#adminButton').isVisible());assert(await friend.locator('#logout').isVisible());
 await admin.locator('#closeAdmin').click();
 assert(await friend.locator('#friendsButton').isVisible());await friend.locator('#friendsButton').click();await friend.locator('#friendUsername').fill('test_admin');await friend.locator('#friendSearch button').click();await friend.locator('[data-action=request]').click();await friend.getByText('申请已发送',{exact:true}).waitFor();
 await admin.locator('#friendsButton').click();await admin.locator('[data-action=accepted]').click();await admin.locator('[data-action=invite]').waitFor();assert(await admin.locator('#friendCount').isHidden());await admin.locator('[data-close=friendsDialog]').click();
 await friend.locator('[data-close=friendsDialog]').click();await admin.locator('#create').click();await admin.locator('#code').filter({hasText:/\d{6}/}).waitFor();const code=await admin.locator('#code').innerText();
 assert(!await admin.locator('#logout').isVisible());
 assert.equal(await admin.locator('.seat.me .level-badge').innerText(),'LV.1');assert(await admin.locator('.seat.me').evaluate(e=>e.classList.contains('level-default')));
 assert.equal(await admin.locator('.seat.me .skin-midnight').count(),0); // Own face-down cards appear only after dealing.
 await admin.locator('#friendsButton').click();await admin.locator('[data-action=invite]').click();await admin.getByText('已处理',{exact:true}).waitFor();await admin.locator('[data-close=friendsDialog]').click();
 await friend.waitForFunction(()=>!document.getElementById('friendCount').hidden);assert.equal(await friend.locator('#friendCount').innerText(),'1');await friend.locator('#friendsButton').click();await friend.locator('[data-action=joinInvite]').click();await friend.locator('#game').waitFor({state:'visible'});
 assert(!await friend.locator('#logout').isVisible());assert(!await friend.locator('#adminButton').isVisible());
 await admin.waitForFunction(()=>!document.getElementById('start').disabled);await admin.locator('#start').click();await Promise.all([admin.locator('#phase').filter({hasText:'翻牌前'}).waitFor(),friend.locator('#phase').filter({hasText:'翻牌前'}).waitFor()]);const adminActs=await admin.locator('#actions').isVisible(),friendActs=await friend.locator('#actions').isVisible();assert.notEqual(adminActs,friendActs,'应只有一名玩家可以行动');const actor=adminActs?admin:friend;assert.equal(await actor.locator('.pot-presets button').count(),4);const half=actor.locator('[data-pot="0.5"]');assert(await half.isEnabled());await half.click();const preset=Number(await actor.locator('#amount').inputValue()),bounds=await actor.locator('#amount').evaluate(e=>({min:Number(e.min),max:Number(e.max)}));assert(preset>=bounds.min&&preset<=bounds.max,'建议下注额应处于合法范围');await actor.locator('#call').click();await admin.waitForTimeout(1200);const adminNext=await admin.locator('#actions').isVisible(),friendNext=await friend.locator('#actions').isVisible();assert.notEqual(adminNext,friendNext,'行动后应只有一名玩家可以继续');const nextPlayer=adminNext?admin:friend;await nextPlayer.waitForFunction(()=>window.__audioTimeline.some(x=>x.file==='your_turn.mp3'&&x.event==='end'));const timeline=await nextPlayer.evaluate(()=>window.__audioTimeline);const actionEnd=timeline.find(x=>['check.mp3','call.mp3'].includes(x.file)&&x.event==='end'),turnStart=timeline.find(x=>x.file==='your_turn.mp3'&&x.event==='start');assert(actionEnd&&turnStart&&turnStart.at>=actionEnd.at,'轮到你语音必须等待上一条行动语音结束');
 assert(await friend.locator('.seat:not(.me) .skin-midnight').count()>0);
 await admin.locator('#manageRoom').click();await admin.locator('#playerManager').getByText('浏览器朋友',{exact:false}).waitFor();await admin.locator('#closeManage').click();
 await friend.locator('#settingsButton').click();assert.equal(await friend.locator('#settingsDialog .skin-option').count(),0);assert(await friend.locator('#soundEnabled').isChecked());assert(await friend.locator('#voiceEnabled').isChecked());const loaded=await friend.evaluate(async()=>Promise.all(['check','call','raise','all_in','fold','your_turn','showdown'].map(async name=>(await fetch(`/audio/voice/${name}.mp3`)).headers.get('content-type'))));assert(loaded.every(type=>type==='audio/mpeg'));await friend.locator('#closeSettings').click();
 await friend.locator('#passwordButton').click();assert(!await friend.locator('#passwordDialog .skin-option').first().isVisible());await friend.locator('#skinSection summary').click();assert.equal(await friend.locator('#passwordDialog .skin-option').count(),4);await friend.locator('#passwordDialog .skin-option[data-skin=ink]').click();await friend.getByText('账号已同步',{exact:false}).waitFor();await friend.locator('#nicknameSection summary').click();await friend.locator('#settingsNickname').fill('朋友新昵称');await friend.locator('#nicknameForm button').click();await friend.getByText('昵称已保存',{exact:true}).waitFor();await friend.locator('#passwordSection summary').click();await friend.locator('#oldPassword').fill(f.secret);await friend.locator('#newPassword').fill('012345');await friend.locator('#passwordForm button').click();await friend.getByText('密码已修改，其他登录已撤销。',{exact:true}).waitFor();await friend.locator('#closePassword').click();
 await friend.reload();await friend.locator('#game').waitFor({state:'visible'});assert.match(await friend.locator('#accountName').innerText(),/LV\.1[\s\S]*朋友新昵称/);assert.equal(await friend.locator('.seat.me .level-badge').innerText(),'LV.1');assert(!await friend.locator('#logout').isVisible());
 await admin.reload();await admin.locator('#game').waitFor({state:'visible'});assert.equal(await admin.locator('#code').innerText(),code);assert.equal(await admin.locator('html').getAttribute('data-table-skin'),'midnight');assert(await admin.locator('.seat').filter({hasText:'朋友新昵称'}).locator('.skin-ink').count()>0);await admin.locator('#adminButton').click();assert(!await admin.locator('#adminUsers').isVisible());assert(!await admin.locator('#adminAudit').isVisible());await admin.locator('#adminRooms').getByText('房间 '+code,{exact:true}).waitFor();await admin.locator('#adminUsersSection summary').click();
 await admin.screenshot({path:fileURLToPath(new URL('./test-output/latest-admin.png',import.meta.url)),fullPage:true});await friend.screenshot({path:fileURLToPath(new URL('./test-output/latest-mobile.png',import.meta.url)),fullPage:true});
 await admin.locator('.admin-user').filter({hasText:'browser_friend'}).getByRole('button',{name:'封禁',exact:true}).click();await friend.locator('#accountGate').waitFor({state:'visible',timeout:20000});assert(!await friend.locator('#game').isVisible());await admin.locator('#adminRooms').getByText('当前没有房间').waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS latest browser: levels + XP rules + skins + settings + register + approval + invite + play + room manager + profile + recovery + monitor + ban');
}finally{await browser?.close();await f.close();}
