const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={bug:'Bug',experience:'体验优化',feature:'功能建议',other:'其他'},statuses={new:'待查看',viewed:'已查看',processing:'处理中',done:'已完成'};
const options=(map,all=false)=>(all?'<option value="">全部</option>':'')+Object.entries(map).map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
async function request(op,extra={},admin=false){const r=await fetch(admin?'/admin-api':'/community-api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,...extra})});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
$('settingsDialog').insertAdjacentHTML('beforeend','<div class="setting-row"><div><strong>意见反馈</strong><small>报告问题或提出功能建议</small></div><button id="feedbackButton">反馈与建议</button></div>');
document.body.insertAdjacentHTML('beforeend',`<dialog id="friendsDialog"><div class="dialog-head"><h2>好友</h2><button data-close="friendsDialog">关闭</button></div><form id="friendSearch"><label for="friendUsername">搜索唯一用户名</label><input id="friendUsername" maxlength="32" required><button>搜索</button></form><div id="friendResult"></div><p id="friendMessage" role="status"></p><h3>进房邀请</h3><div id="friendInvites"></div><h3>好友与申请</h3><div id="friendList"></div></dialog><dialog id="feedbackDialog"><div class="dialog-head"><h2>反馈与建议</h2><button data-close="feedbackDialog">关闭</button></div><form id="feedbackForm"><label for="feedbackType">反馈类型</label><select id="feedbackType">${options(types)}</select><label for="feedbackContent">内容</label><textarea id="feedbackContent" rows="6" maxlength="2000" required></textarea><button class="primary">提交反馈</button></form><p id="feedbackMessage" role="status"></p></dialog>`);
$('adminDialog').querySelector('nav').insertAdjacentHTML('afterbegin',`<details id="adminFeedbackSection"><summary>用户反馈 <span id="feedbackPending"></span></summary><div class="admin-section-body"><div class="community-filters"><label>状态<select id="filterStatus">${options(statuses,true)}</select></label><label>类型<select id="filterType">${options(types,true)}</select></label><label>时间<select id="filterOrder"><option value="desc">最新优先</option><option value="asc">最早优先</option></select></label><button id="feedbackRefresh">刷新</button></div><p id="adminFeedbackMessage" role="status"></p><div id="feedbackItems"></div></div></details>`);
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('friendsButton').onclick=()=>{$('friendsDialog').showModal();refreshFriends();};$('feedbackButton').onclick=()=>$('feedbackDialog').showModal();
let loading=false,generation=0;
async function refreshFriends(){if(loading||$('accountBar').hidden)return;loading=true;const g=generation;try{const d=await request('list');if(g!==generation)return;const n=d.invitations.length+d.friends.filter(f=>f.incoming&&f.status==='pending').length;$('friendCount').textContent=n>9?'9+':String(n);$('friendCount').hidden=!n;$('friendsButton').classList.toggle('has-tasks',!!n);$('friendsButton').setAttribute('aria-label',n?`好友，${n} 项待处理`:'好友');$('friendInvites').innerHTML=d.invitations.map(i=>`<div class="community-row"><span>${esc(i.fromName)} 邀你加入 ${esc(i.roomId)}</span><button data-action="joinInvite" data-id="${i.id}">接受</button><button data-action="dismiss" data-id="${i.id}">忽略</button></div>`).join('')||'<p>暂无邀请</p>';$('friendList').innerHTML=d.friends.map(f=>`<div class="community-row"><span>${esc(f.nickname)} · ${esc(f.username)}<small>${f.status==='pending'?(f.incoming?'向你申请好友':'申请已发送'):({offline:'离线',online:'在线',playing:'游戏中'})[f.presence]}</small></span>${f.status==='pending'?(f.incoming?`<button data-action="accepted" data-id="${f.relationId}">接受</button><button data-action="rejected" data-id="${f.relationId}">拒绝</button>`:''):`<button data-action="invite" data-id="${f.id}" ${f.presence==='offline'?'disabled':''}>邀请进房</button>`}</div>`).join('')||'<p>搜索用户名添加好友</p>';}catch(e){$('friendMessage').textContent=e.message;}finally{loading=false;}}
$('friendSearch').onsubmit=async e=>{e.preventDefault();try{const {user}=await request('search',{username:$('friendUsername').value});$('friendResult').innerHTML=user?`<div class="community-row"><span>${esc(user.nickname)} · ${esc(user.username)}</span><button data-action="request" data-id="${user.id}">加好友</button></div>`:'未找到用户';}catch(e){$('friendMessage').textContent=e.message;}};
$('friendsDialog').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;b.disabled=true;try{const id=b.dataset.id,a=b.dataset.action;if(a==='joinInvite'){const i=await request('invitation',{id});if(await window.pokerJoinRoom(i.roomId)){await request('invitation',{id,dismiss:true});$('friendsDialog').close();}}else if(a==='dismiss')await request('invitation',{id,dismiss:true});else if(['accepted','rejected'].includes(a))await request('respond',{id,status:a});else await request(a,{targetId:id});$('friendMessage').textContent='已处理';await refreshFriends();}catch(e){$('friendMessage').textContent=e.message;}finally{b.disabled=false;}};
$('feedbackForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await request('feedback',{type:$('feedbackType').value,content:$('feedbackContent').value});$('feedbackContent').value='';$('feedbackMessage').textContent='反馈已提交，感谢你的建议';}catch(e){$('feedbackMessage').textContent=e.message;}finally{b.disabled=false;}};
async function loadFeedback(){try{const d=await request('feedbackList',{status:$('filterStatus').value,type:$('filterType').value,order:$('filterOrder').value},true);$('feedbackPending').textContent=`待处理反馈：${d.pending}`;$('feedbackItems').innerHTML=d.items.map(f=>`<form class="feedback-item" data-id="${f.id}"><strong>${esc(f.username)} · ${types[f.type]}</strong><small>${new Date(f.createdAt).toLocaleString()} · v${esc(f.gameVersion)} · 房间 ${esc(f.roomId||'—')} / 第 ${f.handId||'—'} 手</small><p class="feedback-text">${esc(f.content)}</p><label>处理状态<select name="status">${Object.entries(statuses).map(([v,t])=>`<option value="${v}" ${v===f.status?'selected':''}>${t}</option>`).join('')}</select></label><label>管理员备注（仅管理员可见）<textarea name="adminNote" maxlength="2000">${esc(f.adminNote)}</textarea></label><button>保存</button></form>`).join('')||'<p>暂无反馈</p>';}catch(e){$('adminFeedbackMessage').textContent=e.message;}}
$('adminButton').addEventListener('click',loadFeedback);$('feedbackRefresh').onclick=loadFeedback;for(const id of ['filterStatus','filterType','filterOrder'])$(id).onchange=loadFeedback;
$('feedbackItems').onsubmit=async e=>{e.preventDefault();const form=e.target,b=form.querySelector('button');b.disabled=true;try{await request('feedbackUpdate',{id:form.dataset.id,status:form.elements.status.value,adminNote:form.elements.adminNote.value},true);$('adminFeedbackMessage').textContent='已保存';await loadFeedback();}catch(e){$('adminFeedbackMessage').textContent=e.message;}finally{b.disabled=false;}};
window.addEventListener('poker-account-cleared',()=>{generation++;for(const id of ['friendList','friendInvites','friendResult','feedbackItems','friendCount','feedbackPending'])$(id).textContent='';});
setInterval(()=>{if(!document.hidden)refreshFriends();},3000);refreshFriends();
