import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {fixture} from './test-server.mjs';
const {chromium}=createRequire(import.meta.url)('C:/Users/Ziran/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const f=await fixture();let browser;
try{browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(f.base);await page.locator('#username').fill('test_admin');await page.locator('#password').fill(f.secret);await page.locator('#authSubmit').click();await page.locator('#create').click();for(let i=0;i<7;i++)await page.locator('#addbot').click();await page.locator('.seat').nth(7).waitFor();await page.locator('#start').click();await page.locator('.seat:not(.me) .card').first().waitFor();await page.setViewportSize({width:390,height:900});for(const theme of ['classic','ivory','midnight','ink']){const appearance=await page.evaluate(theme=>{document.documentElement.dataset.tableSkin=theme;const felt=getComputedStyle(document.querySelector('.felt')),edge=getComputedStyle(document.querySelector('.felt'),'::after');return {felt:felt.backgroundImage,edge:edge.backgroundImage,maskImage:edge.webkitMaskImage,padding:edge.padding};},theme);assert.equal((appearance.felt.match(/gradient/g)||[]).length,1,`${theme}: central felt must stay visually quiet`);assert(appearance.edge.includes('gradient'));assert.notEqual(appearance.maskImage,'none');assert.equal(appearance.padding,'6px');await page.screenshot({path:`test-output/table-${theme}-390.png`,fullPage:true});}
const levelGeometry=await page.evaluate(()=>{const tiers=[['level-bronze','LV.5'],['level-silver','LV.10'],['level-gold','LV.15'],['level-platinum','LV.20'],['level-diamond','LV.25'],['level-master','LV.30']];document.documentElement.dataset.tableSkin='classic';const seats=[...document.querySelectorAll('.seat')].slice(0,6);seats.forEach((seat,i)=>{seat.className=seat.className.replace(/level-\w+/g,'').trim()+' '+tiers[i][0];const badge=seat.querySelector('.level-badge')||document.createElement('span');badge.className='level-badge';badge.textContent=tiers[i][1];seat.prepend(badge);if(i===5){const rebirth=document.createElement('span');rebirth.className='rebirth-badge';rebirth.textContent='↻';seat.prepend(rebirth);}});return seats.map(seat=>{const box=seat.getBoundingClientRect(),badge=seat.querySelector('.level-badge').getBoundingClientRect(),name=seat.querySelector('.name').getBoundingClientRect();return {inside:badge.left>=box.left&&badge.right<=box.right&&badge.top>=box.top&&badge.bottom<=box.bottom,nameInside:name.right<=box.right,label:seat.querySelector('.level-badge').textContent};});});assert.deepEqual(levelGeometry.map(x=>x.label),['LV.5','LV.10','LV.15','LV.20','LV.25','LV.30']);assert(levelGeometry.every(x=>x.inside&&x.nameInside));await page.screenshot({path:'test-output/level-tiers-390.png',fullPage:true});
for(const width of [320,375,390,430]){await page.setViewportSize({width,height:900});const data=await page.evaluate(()=>{const seats=[...document.querySelectorAll('.seat')],rects=seats.map(s=>s.getBoundingClientRect()),overlaps=[];for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i],b=rects[j];if(Math.min(a.right,b.right)>Math.max(a.left,b.left)&&Math.min(a.bottom,b.bottom)>Math.max(a.top,b.top))overlaps.push([i,j]);}return {rects:rects.map(r=>({x:r.x,y:r.y,w:r.width,h:r.height})),overlaps,outside:rects.filter(r=>r.left<0||r.right>innerWidth).length,cardWidth:document.querySelector('.seat:not(.me) .card').getBoundingClientRect().width,labels:seats.every(s=>s.querySelector('.bet').textContent.includes('本手')&&s.querySelector('.total').textContent.includes('本手累计')&&s.querySelector('.balance').scrollWidth<=s.querySelector('.balance').clientWidth)};});assert.deepEqual(data.overlaps,[],`${width}: overlaps`);assert.equal(data.outside,0,`${width}: outside`);assert(data.labels);assert.equal(data.cardWidth,24);await page.screenshot({path:`test-output/mobile-${width}.png`,fullPage:true});}
await page.locator('#settingsButton').click();await page.locator('#feedbackButton').click();await page.locator('#feedbackContent').fill('移动端反馈测试');await page.locator('#feedbackForm button').click();await page.getByText('反馈已提交，感谢你的建议',{exact:true}).waitFor();await page.locator('[data-close=feedbackDialog]').click();await page.locator('#closeSettings').click();await page.locator('#adminButton').click();await page.locator('#adminFeedbackSection summary').click();await page.locator('.feedback-item').first().waitFor();await page.locator('.feedback-item textarea').fill('已复现');await page.locator('.feedback-item select').selectOption('done');await page.locator('.feedback-item button').click();await page.getByText('已保存',{exact:true}).waitFor();await page.locator('#closeAdmin').click();
// Exercise every rank/suit at the smallest opponent size, checking text geometry.
await page.setViewportSize({width:320,height:900});const overflow=await page.evaluate(()=>{const probe=document.createElement('div');probe.className='seat';document.body.append(probe);const bad=[];for(const suit of ['♠','♥','♦','♣'])for(const rank of ['A','K','Q','J','10','9','8','7','6','5','4','3','2']){probe.innerHTML=`<span class="card">${rank}<small>${suit}</small></span>`;const card=probe.firstChild,r=card.getBoundingClientRect();for(const child of card.childNodes){const range=document.createRange();range.selectNodeContents(child);const b=range.getBoundingClientRect();if(b.left<r.left||b.right>r.right||b.top<r.top||b.bottom>r.bottom)bad.push(rank+suit);}}probe.remove();return bad;});assert.deepEqual(overflow,[]);assert.deepEqual(errors,[]);console.log('PASS four mobile widths, eight seats, all 52 faces, feedback UI');
}finally{await browser?.close();await f.close();}
