import baseTest from 'node:test';import assert from 'node:assert/strict';import {score,compare,player,room,start,act,view,legal,botDecision,botStrength,rebirth} from './engine.mjs';import {progressionConfig,levelForXp,tierForLevel,xpForNet} from './progression.js';
const test=(name,...args)=>name.startsWith('HTTP ')?baseTest.skip(name,...args):baseTest(name,...args);
const c=(rank,suit=0)=>suit*13+rank-2;
test('三人首轮小盲必须补齐，大盲保留过牌权，历史按轮次记录',()=>{const a=player('庄家'),b=player('小盲'),d=player('大盲'),r=room('1',a);r.players.push(b,d);start(r);assert.equal(r.turn,0);act(r,a.id,'call');assert.equal(r.turn,1);assert.equal(b.bet,10);assert.equal(legal(r,b).call,10);assert.equal(r.phase,'preflop');act(r,b.id,'call');assert.equal(b.bet,20);assert.equal(b.stack,1980);assert.equal(r.phase,'preflop');assert.equal(r.turn,2);assert.equal(legal(r,d).call,0);act(r,d.id,'call');assert.equal(r.phase,'flop');assert.equal(r.players.reduce((n,p)=>n+p.total,0),60);assert(r.history.some(e=>e.text.includes('补入 10（本轮共 20）')));assert(r.history.some(e=>e.phase==='flop'&&e.text.includes('公共牌')));assert.equal(b.bet,0);assert.equal(b.action,'等待行动');});
test('小盲积分不足可全下到 15，历史不泄露底牌',()=>{const a=player('庄家'),b=player('小盲'),d=player('大盲'),r=room('1',a);b.stack=15;r.players.push(b,d);start(r);act(r,a.id,'call');assert.equal(legal(r,b).call,5);act(r,b.id,'call');assert.equal(b.total,15);act(r,d.id,'call');assert.equal(r.phase,'flop');assert(r.history.some(e=>e.text.includes('全下跟注')));assert(view(r,a.id).history.every(e=>!('cards' in e)));});
test('牌型：皇家同花顺、轮子顺子、双三条葫芦、踢脚',()=>{assert.deepEqual(score([10,11,12,13,14].map(x=>c(x))),[8,14]);assert.equal(score([c(14),c(2,1),c(3),c(4),c(5)])[1],5);assert.deepEqual(score([c(14),c(14,1),c(14,2),c(13),c(13,1),c(13,2),c(2)]),[6,14,13]);assert(compare([1,10,14,8,7],[1,10,13,12,11])>0);});
test('单挑位置、隐藏底牌、越权行动、弃牌结算',()=>{const a=player('A'),b=player('B'),r=room('1',a);r.players.push(b);start(r);assert.equal(r.turn,r.dealer);assert.equal(a.bet,10);assert.equal(b.bet,20);assert.deepEqual(view(r,a.id).players[1].cards,[-1,-1]);assert.throws(()=>act(r,b.id,'call'));act(r,a.id,'fold');assert.equal(r.phase,'done');assert.equal(a.stack+b.stack,4000);assert.deepEqual(view(r,a.id).players[1].cards,[-1,-1]);});
test('卡背皮肤随玩家公开但不会泄露隐藏底牌',()=>{const a=player('A',false,'device-a','midnight'),b=player('B',false,'device-b','ink'),r=room('1',a);r.players.push(b);start(r);const av=view(r,a.id);assert.equal(av.players.find(p=>p.id===a.id).cardBack,'midnight');assert.equal(av.players.find(p=>p.id===b.id).cardBack,'ink');assert.deepEqual(av.players.find(p=>p.id===b.id).cards,[-1,-1]);assert.equal(player('C',false,'','not-a-skin').cardBack,'classic');});
test('牌桌状态不再重复传输旧版日志',()=>{const a=player('A'),r=room('1',a);for(let i=0;i<300;i++)r.logs.unshift(`旧日志 ${i}`);const state=view(r,a.id);assert.equal('logs' in state,false);});
test('轮询可只传增量历史，同时保留首次进入的完整历史',()=>{const a=player('A'),r=room('1',a);r.history=[];for(let i=1;i<=300;i++){r.eventSequence=i;r.history.push({eventId:String(i),sequence:i,hand:Math.ceil(i/10),phase:'flop',text:'事件 '+i,time:i});}const full=view(r,a.id),delta=view(r,a.id,300);assert.equal(full.history.length,300);assert.equal(full.historyDelta,false);assert.equal(delta.history.length,0);assert.equal(delta.historyDelta,true);assert(JSON.stringify(delta).length<JSON.stringify(full).length/4);r.eventSequence=301;r.history.push({eventId:'301',sequence:301,hand:31,phase:'done',text:'新事件',time:301});assert.deepEqual(view(r,a.id,300).history.map(e=>e.sequence),[301]);});
test('低于继续门槛时可主动补分重生，服务端保留战绩并记录次数与时间',()=>{const a=player('房主'),b=player('玩家'),r=room('1',a);r.players.push(b);assert.throws(()=>rebirth(r,b.id),/仍可继续/);b.stack=0;const beforeRecord=b.stack-b.issued;rebirth(r,b.id,123456);assert.equal(b.stack,progressionConfig.rebirthTargetStack);assert.equal(b.stack-b.issued,beforeRecord);assert.equal(b.rebirthCount,1);assert.equal(b.rebirthAt,123456);assert.equal(view(r,a.id).players.find(p=>p.id===b.id).canRebirth,false);b.stack=0;assert.throws(()=>{r.phase='preflop';rebirth(r,b.id);},/本手结束/);});
test('等级表、阶段边框与单手 XP 上限来自统一配置',()=>{assert.equal(levelForXp(0),1);assert.equal(levelForXp(100),2);assert.equal(levelForXp(2700),10);assert.equal(levelForXp(30000),30);assert.equal(levelForXp(999999),30);assert.equal(tierForLevel(5).key,'bronze');assert.equal(tierForLevel(30).key,'master');assert.equal(xpForNet(-100),0);assert.equal(xpForNet(99),9);assert.equal(xpForNet(10000),100);assert.equal(progressionConfig.levelXp.length,30);});
test('短额全下不重开加注，完整加注后可再次加注',()=>{const a=player('A'),b=player('B'),d=player('C'),r=room('1',a);r.players.push(b,d);d.stack=130;start(r);act(r,a.id,'raise',100);act(r,b.id,'call');act(r,d.id,'raise',130);assert.equal(r.turn,0);assert.equal(legal(r,a).raise,false);assert.throws(()=>act(r,a.id,'raise',250));act(r,a.id,'call');act(r,b.id,'call');assert.equal(r.phase,'flop');});
test('多边池按资格分配，退还未跟注部分',()=>{const a=player('A'),b=player('B'),d=player('C'),r=room('1',a);r.players.push(b,d);a.stack=100;b.stack=200;d.stack=300;start(r);r.board=[c(2),c(4,1),c(7,2),c(9,3),c(11)];r.phase='river';a.cards=[c(14),c(14,1)];b.cards=[c(13),c(13,1)];d.cards=[c(12),c(12,1)];act(r,a.id,'raise',100);act(r,b.id,'raise',200);act(r,d.id,'call');assert.equal(r.phase,'done');assert.deepEqual(r.players.map(p=>p.stack),[300,200,100]);});
test('公共牌平局与奇数筹码守恒',()=>{const a=player('A'),b=player('B'),r=room('1',a);r.players.push(b);start(r);r.board=[10,11,12,13,14].map(x=>c(x));r.phase='river';a.cards=[c(2,1),c(3,1)];b.cards=[c(4,2),c(5,2)];act(r,a.id,'call');act(r,b.id,'call');assert.deepEqual(r.players.map(p=>p.stack),[2000,2000]);});
test('300 局随机行动均终止且积分守恒、发牌不重复',()=>{for(let n=0;n<300;n++){let r=room('1',player('A'));for(let k=1;k<2+n%5;k++)r.players.push(player('P'+k));r.players.forEach((p,i)=>p.stack=30+(n*31+i*67)%900);const total=r.players.reduce((s,p)=>s+p.stack,0);start(r);let steps=0;while(r.phase!=='done'){assert(++steps<200);const p=r.players[r.turn],l=legal(r,p);if(l.raise&&Math.random()<.2)act(r,p.id,'raise',Math.random()<.5?l.min:l.max);else act(r,p.id,Math.random()<.1?'fold':'call');}assert.equal(r.players.reduce((s,p)=>s+p.stack,0),total);const cards=[...r.board,...r.players.flatMap(p=>p.cards)];assert.equal(cards.length,new Set(cards).size);}});
test('八人桌仍可发牌且至少两人即可开始',()=>{const a=player('A'),r=room('1',a);assert.throws(()=>start(r));for(let i=1;i<8;i++)r.players.push(player('P'+i));start(r);assert.equal(r.players.length,8);assert.equal(r.phase,'preflop');assert.equal(r.players.filter(p=>p.cards.length===2).length,8);});
test('基础陪练会按牌力弃牌、过牌、加注，且不读取他人底牌',()=>{const a=player('A'),b=player('陪练',true),r=room('1',a);r.players.push(b);start(r);const p=r.players[r.turn];p.cards=[12,25];const strong=botDecision(r,p,20);assert(botStrength(r,p)>.9);assert.equal(strong.type,'raise');assert(strong.amount>=legal(r,p).min&&strong.amount<=legal(r,p).max);p.cards=[0,18];r.high=500;assert.equal(botDecision(r,p,50).type,'fold');r.high=p.bet;assert.equal(botDecision(r,p,50).type,'call');});
test('基础陪练在二至八人局的决策始终合法并能结束',()=>{for(let n=0;n<200;n++){const r=room('1',player('房主'));for(let i=1;i<2+n%7;i++)r.players.push(player('陪练'+i,true));const total=r.players.reduce((sum,p)=>sum+p.stack,0);start(r);let steps=0;while(r.phase!=='done'){assert(++steps<300);const p=r.players[r.turn],move=botDecision(r,p,(n*17+steps*23)%100);act(r,p.id,move.type,move.amount);}assert.equal(r.players.reduce((sum,p)=>sum+p.stack,0),total);}});
test('HTTP 八人上限、设备恢复、皮肤同步、房内重名、踢人、五小时期限与房主权限',async()=>{const base=process.env.TEST_BASE||'http://localhost:8787',req=async b=>{const res=await fetch(`${base}/api`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return {status:res.status,data:await res.json()};};const a=(await req({op:'create',name:'测试房主',deviceId:'device-host',cardBack:'midnight'})).data;let av=(await req({...a,op:'state'})).data;assert.equal(av.players.find(p=>p.id===a.token).cardBack,'midnight');assert(av.expiresAt-Date.now()>4.9*3600000&&av.expiresAt-Date.now()<=5*3600000);const b=(await req({op:'join',code:a.code,name:'测试朋友',deviceId:'device-friend',cardBack:'ivory'})).data;assert.equal((await req({...b,op:'skin',cardBack:'ink'})).data.players.find(p=>p.id===b.token).cardBack,'ink');const recovered=(await req({op:'join',code:a.code,name:'另一个名字',deviceId:'device-friend',cardBack:'ivory'})).data;assert.equal(recovered.token,b.token);assert.equal(recovered.recovered,true);assert.equal((await req({...b,op:'state'})).data.players.find(p=>p.id===b.token).cardBack,'ivory');assert.equal((await req({op:'join',code:a.code,name:' 测试朋友 ',deviceId:'device-other'})).status,400);for(let i=0;i<6;i++)assert.equal((await req({...a,op:'bot'})).status,200);assert.equal((await req({...a,op:'bot'})).status,400);av=(await req({...a,op:'state'})).data;const bot=av.players.find(p=>p.bot);assert.equal((await req({...b,op:'kick',playerId:bot.id})).status,400);assert.equal((await req({...a,op:'kick',playerId:bot.id})).status,200);av=(await req({...a,op:'state'})).data;assert.equal(av.players.length,7);assert.equal((await req({...b,op:'start'})).status,400);assert.equal((await req({...a,op:'start'})).status,200);assert.equal((await req({...a,op:'kick',playerId:b.token})).status,200);av=(await req({...a,op:'state'})).data;assert.equal(av.players.find(p=>p.id===b.token).pendingKick,true);const bv=(await req({...b,op:'state'})).data;assert.deepEqual(av.players.find(p=>p.id===b.token).cards,[-1,-1]);assert.deepEqual(bv.players.find(p=>p.id===a.token).cards,[-1,-1]);assert.equal((await req({...b,op:'close'})).status,400);assert.equal((await req({...a,op:'close'})).status,200);assert.equal((await req({...a,op:'state'})).status,400);});

test('结算涵盖输家、净额守恒，弃牌胜利不公开手牌',()=>{const a=player('A'),b=player('B'),r=room('1',a);r.players.push(b);start(r);act(r,a.id,'fold');const result=view(r,a.id);assert.equal(result.settlement.length,2);assert.deepEqual(result.settlement.map(x=>[x.invested,x.received,x.net]),[[10,0,-10],[20,30,10]]);assert.equal(result.settlement.reduce((n,x)=>n+x.net,0),0);assert.equal(result.lastSettlement.hand,1);assert.equal(result.lastSettlement.showdown,false);assert(result.lastSettlement.rows.every(x=>x.cards.length===0));start(r);assert.equal(view(r,a.id).settlement.length,0);assert.equal(view(r,a.id).lastSettlement.hand,1);});

test('正常摊牌结算包含公共牌、未弃牌玩家底牌和赢家标识',()=>{const a=player('A'),b=player('B'),r=room('1',a);r.players.push(b);start(r);r.board=[c(2),c(4,1),c(7,2),c(9,3),c(11)];r.phase='river';a.cards=[c(14),c(14,1)];b.cards=[c(13),c(13,1)];act(r,a.id,'call');act(r,b.id,'call');const last=view(r,a.id).lastSettlement;assert.equal(last.showdown,true);assert.equal(last.board.length,5);assert(last.rows.every(x=>x.cards.length===2));assert.equal(last.rows.filter(x=>x.winner).length,1);});

test('标记移出的玩家在本手结算后离开且结算记录仍保留',()=>{const a=player('房主'),b=player('待移出'),r=room('1',a);r.players.push(b);start(r);b.pendingKick=true;act(r,a.id,'fold');assert.equal(r.phase,'done');assert.equal(r.players.some(p=>p.id===b.id),false);assert.equal(r.lastSettlement.rows.some(p=>p.id===b.id),true);});
